version: 2
executors:
  my-custom-executor:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light

jobs:

  okta-login:
    docker:
      - image: perionnet/okta-awscli:latest
    steps:
      - checkout
      - run: |
          # cat /etc/os-release
          # mkdir terraform && cd terraform
          # apt-get install wget -y
          # wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
          # apt-get install unzip -y
          # unzip terraform_0.11.14_linux_amd64.zip
          apt-get update -y
          apt-get upgrade -y
          curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
          apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          apt-get install terraform
          terraform
          cat ~/.okta/config.properties
          sed -i 's;acmecorp.okta.com.changeme.local;axamed.okta.com;g' ~/.okta/config.properties
          cat ~/.okta/config.properties
          pwd

  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - okta-login
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
